import { execFileSync } from 'child_process';
import { createCipheriv, createHash, createHmac, createPrivateKey, createPublicKey, diffieHellman, sign } from 'crypto';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { crc32, gunzipSync, inflateRawSync, inflateSync } from 'zlib';
import { entries, pinned } from './corpus.mjs';

const ether = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const python = process.env.PYTHON ?? 'python3';

const usage = `Usage: node scripts/vectors.mjs [--check]
  Writes the generated test files: tests/corpus.ray (round trips over the pinned corpus, and what a reference
  implementation reads from each file) and tests/reference.ray (what a reference implementation computes for fixed
  inputs), from node:crypto, node:zlib and Pillow (${python}).
  --check   compute them again and exit 1 when a committed file differs (a reference implementation changed, or the
            corpus did)`;

const generator = '@ether/v0.ts/scripts/vectors.mjs';
const subscript = n => String(n).replace(/\d/g, d => '₀₁₂₃₄₅₆₇₈₉'[d]);
const printable = b => b.every(x => x >= 0x20 && x < 0x7f && x !== 0x22 && x !== 0x5c && x !== 0x7b && x !== 0x7d);
const hex = b => Buffer.from(b).toString('hex');
const short = b => hex(b).slice(0, 8) + (b.length > 4 ? '…' : '');

function bytes(b) {
  b = Buffer.from(b);
  if (b.length === 0) return '[]';
  if (b.length > 1 && b.every(x => x === b[0])) return `[0x${b[0].toString(16).padStart(2, '0')}] * ${b.length}`;
  if (b.length > 1 && b.every((x, i) => x === b[0] + i)) return b[0] === 0 ? `0..<${b.length}` : `0x${b[0].toString(16).padStart(2, '0')}..<0x${(b[0] + b.length).toString(16).padStart(2, '0')}`;
  if (b.length <= 64 && printable([...b])) return `"${b.toString('latin1')}".bytes`;
  return `"${hex(b)}" as Hexadecimal${subscript(2 * b.length)} as Byte${subscript(b.length)}`;
}
const hexIs = (expr, b) => `${expr} as Hexadecimal${subscript(2 * b.length)} == "${hex(b)}"`;
const rayString = s => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const name = s => s.replace(/\.[^.]*$/, '').replace(/[^A-Za-z0-9]+/g, '_').replace(/^_|_$/g, '');

class Claims {
  constructor(prefix) { this.prefix = prefix; this.next = 1; this.lines = []; }
  line(s) { this.lines.push(s); }
  claim(condition, what) { this.lines.push(`unless ${condition} { INFO@mark \`${this.prefix}${this.next++} ${what}\` }`); }
}

function file(header, claims) {
  const lines = claims.lines.slice(claims.lines.findIndex(l => l !== ''));
  return [...header.map(l => `// ${l}`), '', 'mark ^keyword := global', '', ...lines, ''].join('\n');
}

function corpusOf(project) {
  const manifest = `$/${project}/tests/corpus/corpus.json`;
  return entries(manifest).filter(e => !/LICENSE$/.test(e.file)).map(e => ({ ...e, bytes: pinned(manifest, e) }));
}

function inflatedVariables(claims, prefix, items) {
  const known = new Map();
  for (const item of items) {
    const key = hex(item.inflated);
    if (!known.has(key)) {
      const variable = `${prefix}_inflated_${known.size + 1}`;
      known.set(key, variable);
      claims.line(`${variable} := ${bytes(item.inflated)}`);
    }
    item.inflatedName = known.get(key);
  }
}

function streamCorpus({ project, prefix, language, read, as, extra, header }) {
  const c = new Claims(prefix);
  const items = corpusOf(project).map(e => ({ ...e, inflated: read.inflate(e.bytes) }));
  inflatedVariables(c, project, items);
  for (const e of items) {
    const v = `${project}_${name(e.file)}`;
    const shape = as(e.bytes);
    c.line('');
    c.line(`// ${e.file}: ${e.note}`);
    c.line(`${v} := ${bytes(e.bytes)}`);
    c.claim(`${shape.holds(`(${v} as ${shape.type})`)} && (${v} as ${shape.type}) as Byte[] == ${v}`, `${e.file} read as ${shape.called} and written back is not the same bytes`);
    c.claim(`${language}.read(${v}) == ${e.inflatedName}`, `${e.file} does not inflate to what ${read.by} gives`);
    c.claim(`${language}.read(${language}.write(${language}.read(${v})) as Byte[]) == ${e.inflatedName}`, `${e.file} inflated, written again and inflated is not what ${read.by} gives`);
    for (const [condition, what] of extra(e, v)) c.claim(condition, what);
  }
  return file([header, `Generated by ${generator}; do not edit, run it again.`], c);
}

const zlibCorpus = () => streamCorpus({
  project: 'zlib', prefix: 'ZLC', language: 'Zlib', read: { inflate: inflateSync, by: 'node:zlib inflateSync' },
  as: () => ({ type: 'Zlib', called: 'Zlib', holds: x => `${x} is Zlib` }),
  extra: (e, v) => [[`(${v} as Zlib).window == ${e.bytes[0] >> 4} && (${v} as Zlib).compression == ${e.bytes[1] >> 6}`, `${e.file} does not read CINFO ${e.bytes[0] >> 4} and FLEVEL ${e.bytes[1] >> 6} from its first two bytes`]],
  header: 'ZLIB streams of the pinned corpus (tests/corpus/corpus.json): each read as Zlib and written back, and inflated as node:zlib inflates it.',
});

const gzipCorpus = () => streamCorpus({
  project: 'gzip', prefix: 'GZC', language: 'Gzip', read: { inflate: gunzipSync, by: 'node:zlib gunzipSync' },
  as: b => (members => members > 1
    ? { type: 'Gzip[]', called: `${members} Gzip members`, holds: x => `${x}.count == ${members}` }
    : { type: 'Gzip', called: 'Gzip', holds: x => `${x} is Gzip` })(memberCount(b)),
  extra: () => [],
  header: 'GZIP files of the pinned corpus (tests/corpus/corpus.json): each read as Gzip and written back, and inflated as node:zlib gunzips it.',
});

const deflateCorpus = () => streamCorpus({
  project: 'deflate', prefix: 'DFC', language: 'Deflate', read: { inflate: inflateRawSync, by: 'node:zlib inflateRawSync' },
  as: () => ({ type: 'Deflate.Stream', called: 'a Deflate stream', holds: x => `${x} is Deflate.Stream` }),
  extra: (e, v) => [[`(${v} as Deflate.Stream).blocks.first.kind == ${(e.bytes[0] >> 1) & 3}`, `the first block of ${e.file} is not of BTYPE ${(e.bytes[0] >> 1) & 3}, as its first byte says`]],
  header: 'Raw DEFLATE streams of the pinned corpus (tests/corpus/corpus.json): each read as a Deflate stream and written back, and inflated as node:zlib inflates it.',
});

function memberCount(b) {
  let count = 0;
  for (let at = 0; at < b.length; count++) {
    let end = at + 18;
    while (!completes(b.subarray(at, end))) if (++end > b.length) throw new Error('a gzip member does not end');
    at = end;
  }
  return count;
}

function completes(member) {
  try { gunzipSync(member); return true; } catch { return false; }
}

function pillow(files) {
  const script = [
    'import json, sys',
    'from PIL import Image',
    'out = {}',
    'for path in sys.argv[1:]:',
    '    try:',
    '        im = Image.open(path)',
    '        im.load()',
    '        rgba = im.convert("RGBA")',
    '        w, h = rgba.size',
    '        points = sorted({(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1), (w // 2, h // 2), (w // 3, (2 * h) // 3)})',
    '        out[path] = {"width": w, "height": h, "pixels": [[x, y, list(rgba.getpixel((x, y)))] for x, y in points]}',
    '    except Exception as e:',
    '        out[path] = {"error": type(e).__name__}',
    'print(json.dumps(out))',
  ].join('\n');
  try {
    return JSON.parse(execFileSync(python, ['-c', script, ...files], { encoding: 'utf8' }));
  } catch (e) {
    throw new Error(`Pillow is the reference PNG reader and could not run (${python}): ${e.message.split('\n')[0]}. Install it (pip install pillow) or set PYTHON.`);
  }
}

function pngCorrupt(b) {
  if (!b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return 'its signature is not that of PNG';
  for (let at = 8; at < b.length;) {
    const size = b.readUInt32BE(at), type = b.toString('latin1', at + 4, at + 8);
    if (b.readUInt32BE(at + 8 + size) !== crc32(b.subarray(at + 4, at + 8 + size)) >>> 0) return `the CRC of its ${type} chunk is not the one node:zlib computes`;
    at += 12 + size;
  }
  return undefined;
}

const color = ([r, g, b, a]) => `Geometry.Color(${r}, ${g}, ${b}, ${a === 255 ? 1 : a === 0 ? 0 : `${a} / 255`})`;

function pngCorpus() {
  const c = new Claims('PNGC');
  const items = corpusOf('png');
  const read = pillow(items.map(e => join(ether, '$/png/tests/corpus', e.file)));
  for (const e of items) {
    const v = `png_${name(e.file)}`;
    const reference = read[join(ether, '$/png/tests/corpus', e.file)];
    const corrupt = pngCorrupt(e.bytes);
    c.line('');
    c.line(`// ${e.file}${e.note ? `: ${e.note}` : ''}`);
    c.line(`${v} := ${bytes(e.bytes)}`);
    if (e.valid === false) {
      if (!corrupt) throw new Error(`${e.file} is marked invalid but its signature and every CRC hold`);
      c.claim(`PNG.read(${v}) is Diagnostic`, `${e.file} reads, though ${corrupt}`);
      continue;
    }
    if (corrupt) throw new Error(`${e.file}: ${corrupt}`);
    if (reference.error) throw new Error(`Pillow does not read ${e.file}: ${reference.error}`);
    const size = `.width == ${reference.width} && .height == ${reference.height}`;
    const colours = reference.pixels.map(([x, y, p]) => `.[${y}][${x}] == ${color(p)}`).join(' && ');
    c.claim(`(${v} as PNG) is PNG && (${v} as PNG) as Byte[] == ${v}`, `${e.file} read as PNG and written back is not the same bytes`);
    c.claim(`PNG.read(${v}) -- (${size})`, `${e.file} is not ${reference.width} by ${reference.height} as Pillow reads it`);
    c.claim(`PNG.read(${v}) -- (${colours})`, `${e.file} does not hold the colours Pillow reads at ${reference.pixels.map(([x, y]) => `(${x}, ${y})`).join(', ')}`);
    c.claim(`PNG.read(PNG.write(PNG.read(${v})) as Byte[]) -- (${size} && ${colours})`, `${e.file} read, written again and read does not hold what Pillow reads`);
  }
  return file([`PngSuite images of the pinned corpus (tests/corpus/corpus.json): each read as PNG and written back, read for its size and some colours as Pillow reads`,
    `them (as 8-bit RGBA), and the invalid ones refused. Generated by ${generator}; do not edit, run it again.`], c);
}

function jsonShape(value, read) {
  if (Array.isArray(value)) return `${read}.count == ${value.length}`;
  if (value === null) return `${read} === None`;
  if (typeof value === 'boolean') return `${read} == ${value}`;
  if (typeof value === 'number' && /^-?\d+(\.\d+)?$/.test(String(value))) return `${read} == ${value}`;
  if (typeof value === 'string' && printable([...Buffer.from(value)])) return `${read} == "${value}"`;
  if (typeof value === 'object') return `${read}.entries.count == ${Object.keys(value).length}`;
  return undefined;
}

function jsonCorpus() {
  const c = new Claims('JNC');
  for (const e of corpusOf('json')) {
    const text = e.bytes.toString('latin1');
    const v = `json_${name(e.file)}`;
    let parsed, accepted;
    try { parsed = JSON.parse(text); accepted = true; } catch { accepted = false; }
    if (accepted !== e.valid) throw new Error(`${e.file}: node's JSON.parse ${accepted ? 'accepts' : 'rejects'} it, the manifest says otherwise`);
    c.line('');
    c.line(`${v} := ${rayString(text)}`);
    if (!accepted) { c.claim(`JSON.read(${v}) is Diagnostic`, `${e.file} reads, though node's JSON.parse refuses it`); continue; }
    c.claim(`(${v} as JSON) is JSON && (${v} as JSON) as String == ${v}`, `${e.file} read as JSON and written back is not the same text`);
    if (/^y_object_duplicated/.test(e.file)) continue;
    c.claim(jsonShape(parsed, `JSON.read(${v})`), `${e.file} does not read as node's JSON.parse reads it`);
    c.claim(jsonShape(parsed, `JSON.read($.json.write(JSON.read(${v})))`), `${e.file} read, written again and read is not what node's JSON.parse reads`);
  }
  return file([`JSONTestSuite texts of the pinned corpus (tests/corpus/corpus.json): a y_ text reads as node's JSON.parse reads it and writes back, an n_ text`,
    `is refused as node's JSON.parse refuses it. Generated by ${generator}; do not edit, run it again.`], c);
}

const fixedInputs = [
  Buffer.from(''), Buffer.from('a'), Buffer.from('abc'), Buffer.from('message digest'), Buffer.from('abcdefghijklmnopqrstuvwxyz'),
  Buffer.from('The quick brown fox jumps over the lazy dog'), Buffer.from([...Array(256).keys()]), Buffer.alloc(32, 0), Buffer.alloc(32, 0xff),
];
const boundaries = [55, 56, 63, 64, 65, 111, 112, 119, 120, 127, 128, 129].map(n => ({ n, b: Buffer.alloc(n, 0x61) }));
const inputExpr = b => b.length > 64 && b.every(x => x === 0x61) ? `("a" * ${b.length}).bytes` : bytes(b);
const describe = b => b.length === 0 ? 'no bytes' : b.length > 64 && b.every(x => x === 0x61) ? `${b.length} a's` : printable([...b]) ? `"${b.toString('latin1')}"` : `${bytes(b).replace(/ as Hexadecimal.*$/, '').slice(0, 20)}`;

function crcReference() {
  const c = new Claims('CRCR');
  for (const b of [...fixedInputs, ...boundaries.map(x => x.b)]) {
    const value = crc32(b) >>> 0;
    c.claim(`${inputExpr(b)} as CRC32 as Binary₃₂ == 0x${value.toString(16).padStart(8, '0')}`, `the CRC-32 of ${describe(b)} is not ${value.toString(16).padStart(8, '0')}, as node:zlib computes it`);
  }
  return file([`CRC-32 of fixed inputs as node:zlib's crc32 computes them. Generated by ${generator}; do not edit, run it again.`], c);
}

function shaReference(digest, prefix, algorithm, size) {
  const c = new Claims(prefix);
  for (const b of [...fixedInputs, ...boundaries.map(x => x.b)]) {
    const value = createHash(algorithm).update(b).digest();
    c.claim(`${digest}.write(${inputExpr(b)}) as Byte${subscript(size)} as Hexadecimal${subscript(2 * size)} == "${hex(value)}"`, `${digest} of ${describe(b)} is not ${short(value)}, as node:crypto computes it`);
  }
  return file([`${digest} digests of fixed inputs, among them the lengths around the padding's block boundaries, as node:crypto computes them.`,
    `Generated by ${generator}; do not edit, run it again.`], c);
}

function hmacReference() {
  const c = new Claims('HMACR');
  for (const [digest, algorithm] of [['SHA1', 'sha1'], ['SHA256', 'sha256'], ['SHA512', 'sha512']]) {
    for (const keyLength of [0, 1, 63, 64, 65, 127, 128, 129]) {
      const key = Buffer.alloc(keyLength, 0x6b), message = Buffer.from('ray');
      const value = createHmac(algorithm, key).update(message).digest();
      c.claim(hexIs(`HMAC(${digest}, key: ${bytes(key)}).write(${bytes(message)}).bytes`, value), `HMAC-${digest} with a key of ${keyLength} bytes is not ${short(value)}, as node:crypto computes it`);
    }
  }
  return file([`HMAC over SHA-1, SHA-256 and SHA-512 with keys around each digest's block size, as node:crypto computes it.`,
    `Generated by ${generator}; do not edit, run it again.`], c);
}

function base64Reference() {
  const c = new Claims('BASER');
  const inputs = [...fixedInputs, Buffer.from([0xfb, 0xff]), Buffer.from([0xff, 0xfe, 0xfd, 0xfc])];
  for (const b of inputs) {
    const text = b.toString('base64');
    c.claim(`${bytes(b)} as Base64 as String == "${text}"`, `${describe(b)} is not ${text.slice(0, 12)}${text.length > 12 ? '…' : ''} in Base64, as node's Buffer writes it`);
    c.claim(`Base64.read("${text}") == ${bytes(b)}`, `${text.slice(0, 12)}${text.length > 12 ? '…' : ''} does not read back as ${describe(b)}, as node's Buffer reads it`);
  }
  return file([`Base64 of fixed inputs as node's Buffer writes and reads it. Generated by ${generator}; do not edit, run it again.`], c);
}

function chachaReference() {
  const c = new Claims('CCPR');
  const key = Buffer.from([...Array(32).keys()]), nonce = Buffer.from('000000000000004a00000000', 'hex');
  for (const [length, aad] of [[0, Buffer.alloc(0)], [1, Buffer.alloc(0)], [63, Buffer.from('ray')], [64, Buffer.from('ray')], [65, Buffer.alloc(16, 0xaa)], [129, Buffer.alloc(17, 0xaa)]]) {
    const text = Buffer.alloc(length, 0x2a);
    const cipher = createCipheriv('chacha20-poly1305', key, nonce, { authTagLength: 16 });
    cipher.setAAD(aad, { plaintextLength: length });
    const sealed = Buffer.concat([cipher.update(text), cipher.final(), cipher.getAuthTag()]);
    c.claim(hexIs(`ChaCha20Poly1305.sealed(0..<32, ${bytes(nonce)}, ${bytes(aad)}, ${bytes(text)})`, sealed), `${length} bytes sealed with ${aad.length} bytes of associated data are not ${short(sealed)}, as node:crypto seals them`);
  }
  for (const counter of [0, 1, 2]) {
    const iv = Buffer.alloc(16); iv.writeUInt32LE(counter, 0); nonce.copy(iv, 4);
    const block = createCipheriv('chacha20', key, iv).update(Buffer.alloc(64));
    c.claim(hexIs(`ChaCha20Poly1305.block(0..<32, ${counter}, ${bytes(nonce)})`, block), `the block for counter ${counter} is not ${short(block)}, as node:crypto's chacha20 gives it`);
  }
  return file([`ChaCha20 blocks and the ChaCha20-Poly1305 AEAD over fixed inputs, as node:crypto computes them. Generated by ${generator}; do not edit, run it again.`], c);
}

const der = { x25519: ['302e020100300506032b656e04220420', '302a300506032b656e032100'], ed25519: ['302e020100300506032b657004220420', '302a300506032b6570032100'] };
const privateKey = (kind, secret) => createPrivateKey({ key: Buffer.concat([Buffer.from(der[kind][0], 'hex'), secret]), format: 'der', type: 'pkcs8' });
const publicOf = key => createPublicKey(key).export({ format: 'der', type: 'spki' }).subarray(12);
const secrets = kind => [1, 2, 3].map(i => createHash('sha256').update(`ray ${kind} ${i}`).digest());

function x25519Reference() {
  const c = new Claims('XDHR');
  const keys = secrets('x25519').map(s => ({ s, key: privateKey('x25519', s) }));
  for (const k of keys) { k.public = publicOf(k.key); c.claim(hexIs(`X25519.public(${bytes(k.s)})`, k.public), `the public key of the secret ${short(k.s)} is not ${short(k.public)}, as node:crypto derives it`); }
  for (const [a, b] of [[0, 1], [1, 2], [2, 0]]) {
    const shared = diffieHellman({ privateKey: keys[a].key, publicKey: createPublicKey({ key: Buffer.concat([Buffer.from(der.x25519[1], 'hex'), keys[b].public]), format: 'der', type: 'spki' }) });
    c.claim(hexIs(`X25519.agreed(${bytes(keys[a].s)}, ${bytes(keys[b].public)})`, shared), `the secrets ${short(keys[a].s)} and ${short(keys[b].s)} do not agree on ${short(shared)}, as node:crypto agrees`);
  }
  return file([`X25519 public keys and shared secrets for fixed secrets (SHA-256 of "ray x25519 1" to "3"), as node:crypto computes them.`,
    `Generated by ${generator}; do not edit, run it again.`], c);
}

function ed25519Reference() {
  const c = new Claims('EDSR');
  for (const s of secrets('ed25519')) {
    const key = privateKey('ed25519', s), pub = publicOf(key);
    c.claim(hexIs(`Ed25519.public(${bytes(s)})`, pub), `the public key of the secret ${short(s)} is not ${short(pub)}, as node:crypto derives it`);
    for (const message of [Buffer.alloc(0), Buffer.from('ray')]) {
      const signature = sign(null, message, key);
      c.claim(hexIs(`Ed25519.sign(${bytes(s)}, ${bytes(message)})`, signature), `the secret ${short(s)} does not sign ${describe(message)} as ${short(signature)}, as node:crypto signs it`);
    }
  }
  return file([`Ed25519 public keys and signatures for fixed secrets (SHA-256 of "ray ed25519 1" to "3"), as node:crypto computes them.`,
    `Generated by ${generator}; do not edit, run it again.`], c);
}

export const generated = {
  '$/zlib/tests/corpus.ray': zlibCorpus,
  '$/gzip/tests/corpus.ray': gzipCorpus,
  '$/deflate/tests/corpus.ray': deflateCorpus,
  '$/png/tests/corpus.ray': pngCorpus,
  '$/json/tests/corpus.ray': jsonCorpus,
  '$/crc32/tests/reference.ray': crcReference,
  '$/sha1/tests/reference.ray': () => shaReference('SHA1', 'SHIR', 'sha1', 20),
  '$/sha256/tests/reference.ray': () => shaReference('SHA256', 'SHTR', 'sha256', 32),
  '$/sha512/tests/reference.ray': () => shaReference('SHA512', 'SHFR', 'sha512', 64),
  '$/hmac/tests/reference.ray': hmacReference,
  '$/base64/tests/reference.ray': base64Reference,
  '$/chacha20poly1305/tests/reference.ray': chachaReference,
  '$/x25519/tests/reference.ray': x25519Reference,
  '$/ed25519/tests/reference.ray': ed25519Reference,
};

function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) { console.log(usage); return; }
  const check = args.includes('--check');
  const differing = [];
  for (const [path, make] of Object.entries(generated)) {
    const text = make();
    const at = join(ether, path);
    const committed = existsSync(at) ? readFileSync(at, 'utf8') : undefined;
    if (check) {
      if (committed !== text) differing.push(path);
      console.log(`${path.padEnd(44)} ${committed === text ? 'same' : committed === undefined ? 'MISSING' : 'DIFFERS'}`);
    } else {
      if (committed !== text) writeFileSync(at, text);
      console.log(`${path.padEnd(44)} ${committed === text ? 'unchanged' : 'written'}`);
    }
  }
  if (differing.length > 0) {
    console.log(`\n${differing.length} generated files differ from what the reference implementations give now; run node scripts/vectors.mjs and review the change.`);
    process.exit(1);
  }
}

main();
